# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly    
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("TraitSimulation"); Pkg.test("TraitSimulation"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SnpArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
#  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("TraitSimulation")); include(joinpath("docs", "make.jl"))'
