site_name:           TraitSimulation.jl
repo_url:            https://github.com/huwenboshi/TraitSimulation.jl
site_description:    A julia module to perform trait simulation
site_author:         Huwenbo Shi
theme:               material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - smarty
  - admonition

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Getting Started: example/example.md
- Model Specifications: model/model.md
- Generate Simulations: generate/generate.md
- Link Functions: link/link.md
- Response Distributions: dist/dist.md
